export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
